name: CI/CD
on:
  push:
    branches: [ dev ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint code
        run: |
          autopep8 --recursive --in-place --aggressive --aggressive .
      - name: Run Tests
        run: |
          export API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}
          export AWS_ACCESS_KEY_ID=1
          export AWS_SECRET_ACCESS_KEY=1
          export AWS_S3_BUCKET=1
          export TEST_DB_URI=sqlite:///:memory:
          export S3_FOLDER='static/'
          export CSV_FOLDER='src/static/csv'
          export TEST_PASSWORD=123456
          export FLASK_ENV=testing
          export JWT_SECRET_KEY=duck
          export SECRET_KEY=duck
          export GH_TEST=1
          export FLASK_APP=run.py
          sudo python -m unittest discover src/tests/ -v
