name: CI/CD
on:
  push:
    branches: [ dev ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint code
        run: |
          autopep8 --recursive --in-place --aggressive --aggressive .
      - name: Run Tests
        run: |
          export GH_TEST=1
          python -m unittest discover src/tests/