name: deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: c-sign.in
          username: flask
          key: ${{ secrets.GH_ACTIONS }}
          port: 22
          script: |
            cd /home/flask
            rm -rf csign
            git clone https://github.com/petelah/csign.git
            python3.8 -m venv /home/flask/csign/venv
            /home/flask/csign/venv/bin/pip3.8 install wheel
            /home/flask/csign/venv/bin/pip3.8 install -r /home/flask/csign/requirements.txt
            cd /home/flask/csign
            touch .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "SQLALCHEMY_TRACK_MODIFICATIONS=${{ secrets.SQLALCHEMY_TRACK_MODIFICATIONS }}" >> .env
            echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            export SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }}
            export SQLALCHEMY_TRACK_MODIFICATIONS=${{ secrets.SQLALCHEMY_TRACK_MODIFICATIONS }}
            export MAIL_SERVER=${{ secrets.MAIL_SERVER }}
            export MAIL_PORT=${{ secrets.MAIL_PORT }}
            export MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}
            export MAIL_USERNAME=${{ secrets.MAIL_USERNAM }}
            export MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            export FLASK_APP='run.py'
            export FLASK_ENV='production'
            export FLASK_DEBUG=0
            export PYTHONPATH=$PYTHONPATH:.
            sudo systemctl stop csign
            sudo systemctl start csign
            sudo systemctl enable csign
            sudo systemctl restart nginx