on:
  push:
    branches: [ main ]

name: Deploy to Amazon ECS

jobs:
  update-image:
    name: Update New Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: c-sign
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  deploy-new-version:
    name: Update service
    runs-on: ubuntu-latest
    needs: update-image
    steps:
      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Retrieve JSON Data for Latest Task Definition
        run: >
          aws ecs describe-task-definition
          --task-definition c-sign-web-server
          --query taskDefinition > task_definition.json
      - name: Generate JSON for New Task Definition
        id: update-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          IMAGE: "c-sign:${{ needs.update-image.outputs.image }}"
        with:
          task-definition: task_definition.json
          container-name: c-sign
          image: ${{ env.IMAGE }}
      - name: Test
        run: cat ${{ steps.update-task-definition.outputs.task-definition }}
      - name: Update Task Definition in ECS and Deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.update-task-definition.outputs.task-definition }}
          service: c-sign-server
          cluster: C-S
          wait-for-service-stability: true